using Test
using Sturm

@testset "Sturm.jl" begin
    include("test_orkan_ffi.jl")
    include("test_primitives.jl")
    include("test_bell.jl")
    include("test_teleportation.jl")
    include("test_when.jl")
    include("test_gates.jl")
    include("test_rus.jl")
    include("test_qint.jl")
    include("test_patterns.jl")
    include("test_channel.jl")
    include("test_draw.jl")
    include("test_pixels.jl")
    include("test_passes.jl")
    include("test_density_matrix.jl")
    include("test_density_matrix_mc.jl")
    include("test_noise.jl")
    include("test_qecc.jl")
    include("test_grover.jl")
    include("test_memory_safety.jl")
    include("test_simulation.jl")
    include("test_qdrift.jl")
    include("test_composite.jl")
    include("test_error_bounds.jl")
    include("test_promotion.jl")
    include("test_block_encoding.jl")
    include("test_qsvt_conventions.jl")
    include("test_qsvt_polynomials.jl")
    include("test_qsvt_phase_factors.jl")
    include("test_qsvt_reflect.jl")
    include("test_oaa.jl")
    include("test_bennett_integration.jl")
    include("test_p9_auto_dispatch.jl")
    include("test_multi_path_arithmetic.jl")
    include("test_qint_bitwise.jl")
    include("test_qint_shifts.jl")
    include("test_implicit_cast.jl")
end
