using Test
using Sturm

@testset "Sturm.jl" begin
    include("test_orkan_ffi.jl")
    include("test_rule11_lint.jl")
    include("test_docs_physics_lint.jl")
    include("test_primitives.jl")
    include("test_bell.jl")
    include("test_teleportation.jl")
    include("test_when.jl")
    include("test_control_api.jl")
    include("test_gates.jl")
    include("test_rus.jl")
    include("test_qint.jl")
    include("test_qmod.jl")
    include("test_patterns.jl")
    include("test_arithmetic.jl")
    include("test_channel.jl")
    include("test_draw.jl")
    include("test_pixels.jl")
    include("test_passes.jl")
    include("test_passes_registry.jl")
    include("test_density_matrix.jl")
    include("test_density_matrix_mc.jl")
    include("test_tracing_deep_when.jl")
    include("test_noise.jl")
    include("test_qecc.jl")
    include("test_steane_syndrome.jl")
    include("test_steane_channel_correct.jl")
    include("test_grover.jl")
    include("test_memory_safety.jl")
    include("test_simulation.jl")
    include("test_qdrift.jl")
    include("test_composite.jl")
    include("test_error_bounds.jl")
    include("test_promotion.jl")
    include("test_block_encoding.jl")
    include("test_qsvt_conventions.jl")
    include("test_qsvt_polynomials.jl")
    include("test_qsvt_phase_factors.jl")
    include("test_qsvt_reflect.jl")
    include("test_oaa.jl")
    include("test_bennett_integration.jl")
    include("test_p9_auto_dispatch.jl")
    include("test_multi_path_arithmetic.jl")
    include("test_qint_bitwise.jl")
    include("test_qint_shifts.jl")
    include("test_implicit_cast.jl")
    include("test_hardware_protocol.jl")
    include("test_hardware_simulator.jl")
    include("test_hardware_transport.jl")
    include("test_hardware_context.jl")
    include("test_hardware_recycle.jl")
    include("test_hardware_rus.jl")
    include("test_hardware_qecc.jl")
    include("test_hardware_tcp.jl")
    include("test_hardware_lifecycle.jl")
    include("test_cases.jl")
    include("test_openqasm_cases.jl")
    include("test_cases_consumer_policy.jl")
    include("test_autocleanup.jl")
    include("test_compact_state.jl")
    include("test_compact_state_dm.jl")
    include("test_do_block_alloc.jl")
    include("test_oracle_cache_lru.jl")
    include("test_ptrace.jl")
    include("test_bench_shor_scaling.jl")

    # ── Bead Sturm.jl-4gom: previously orphaned test files. ─────────────────
    # These exercise live src/ that had ZERO default CI coverage. All gated
    # behind STURM_FULL_TEST=1 for now — the Shor and windowed-arithmetic
    # files are known slow and the rest haven't been timed against a
    # default-CI budget. Promote individual files out of the gate as they
    # demonstrate sub-30s wall on a clean precache.
    if get(ENV, "STURM_FULL_TEST", "0") == "1"
        include("test_q84_types.jl")
        include("test_b3l_runway.jl")
        include("test_qrunway_mid.jl")
        include("test_p1z_add_qft_quantum.jl")
        include("test_bennett_compact.jl")
        include("test_6xi_coset.jl")
        include("test_shor.jl")
        include("test_6bn_ekera_hastad.jl")
        include("test_windowed_arithmetic.jl")
    end
end
